# Generated by Django 4.1.7 on 2023-04-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_avatar_description_avatar_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
